name: Inverse conversion CSV from Weblate

on:
  push:
    branches:
      - main
    paths:
      - "samples/monolingual/weblate/**.csv"

jobs:
  convert-job:
    runs-on: ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Conversion
      uses: ./action.yml
      id: conversion
      with:
        invert: true
        multi: false
        original_csv: samples/monolingual/original/*.csv
        weblate_csv: samples/monolingual/weblate/*.csv
        columns: context,source,target,developer_comments
        header: false
        quoting: false

    - name: Create PR
      uses: peter-evans/create-pull-request@v8
      with:
        commit-message: "Auto convert CSV"
        title: "Convert CSV files"
        body: |
          This PR was created automatically by the Convert CSV workflow.
          
          ${{ steps.conversion.outputs.stats }}
        branch: translation-update-${{ github.run_id }}
        base: main
        delete-branch: false
