name: Convert CSV for Weblate (single language to translate)

on:
  push:
    branches:
      - main
    paths:
      - "samples/single/original/**.csv"

jobs:
  convert-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Conversion
        id: conversion
        uses: ./
        with:
          invert: true
          multi: false
          original_csv: samples/single/original/localization_*.csv
          weblate_csv: samples/single/weblate/localization_*.csv
          columns: context,source,target,developer_comment
          header: false
          quoting: false

      - name: create-pr
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "Auto convert CSV"
          title: "Convert CSV files"
          body: |
            This PR was created automatically by the Convert CSV workflow.
            
            ${{ steps.conversion.outputs.stats }}
          branch: translation-update-${{ github.run_id }}
          base: main
          delete-branch: false
